<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>homepage</title>
</head>
	<body>
		<!-- <div class="row"> -->
		<div class="col-md-4"></div>
			<div class="col-md-4">
				<h1 class="text-center">pc achieve</h1>
			</div>
		<div class="jumbotron"></div>
		 <div class="container center_div">
						<!-- <div class="jumbotron">
 -->					       <a class="left" href="#" role="button">login</a>
					       <a class="right" href="#" role="button">register</a>
					        <?php require_once "login.phtml"; ?>
					        <?php require_once "register.phtml"; ?>
				      </div>
				      </div>
	</body>
	<script type="text/javascript" src="pc_achieve/packages/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="pc_achieve/packages/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="pc_achieve/packages/toastr/toastr.min.js"></script>
	<script type="text/javascript" src="pc_achieve/js/homepage.js"></script>
	<script type="text/javascript" src="pc_achieve/js/actionReporter.js"></script>
</html>