<div class="container register">
	
	<div class="col-xs-6 col-md-4">
	  <form>
	    <div class="form-group marginPlus">
	      <label for="email">Name:</label>
	      <input type="text" class="form-control" id="name" placeholder="Enter name">
	    </div>
	     <div class="form-group">
	      <label for="pwd">email:</label>
	      <input type="email" class="form-control" id="email" placeholder="Enter email">
	    </div>
	     <div class="form-group">
	      <label for="pwd">repeat email:</label>
	      <input type="email" class="form-control" id="email2" placeholder="Enter email">
	    </div>
	    <div class="form-group">
	      <label for="pwd">Password:</label>
	      <input type="password" class="form-control" id="pwd" placeholder="Enter password">
	    </div>
	    <button type="submit" class="btn btn-primary col-md-5 col-sm-offset-4 mb">Register</button>
	  </form>
	</div>
</div>